# Generated by Django 3.2.9 on 2022-01-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20211231_1547'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('suppliers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
