# Generated by Django 3.2.9 on 2022-01-13 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(?:0|98|\\+98|\\+980|0098|098|00980)?(9\\d{9})$')], verbose_name='Mobile Number'),
        ),
    ]
