# Generated by Django 3.2.9 on 2022-01-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_mobile_submitted',
            field=models.BooleanField(default=False, verbose_name='is mobile submitted'),
        ),
    ]
