# Generated by Django 3.2.9 on 2021-12-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Post Categorie'},
        ),
    ]
