# Generated by Django 3.2.9 on 2021-12-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('category_image', models.ImageField(upload_to='categoryImage/', verbose_name='Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Comment Text')),
                ('email', models.EmailField(max_length=254, verbose_name='Email_Address')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Feature Title')),
                ('value', models.CharField(max_length=100, verbose_name='Feature Value')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_short_description', models.TextField(verbose_name='Product Short Description')),
                ('product_main_image', models.ImageField(upload_to='productImage/', verbose_name='Product Main Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Product Price')),
                ('discount_available', models.BooleanField(default=False, verbose_name='Discount Available')),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Discount Percent')),
                ('text', models.TextField(verbose_name='Product Main Text')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('update_at', models.DateField(auto_now_add=True, verbose_name='Update At')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('stock', models.IntegerField(default=0, verbose_name='Number Of Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_image', models.ImageField(upload_to='productImage/', verbose_name='Sub Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50, verbose_name='Shop Name')),
                ('shop_address', models.TextField(max_length=200, verbose_name='Shop Address')),
                ('shop_phone', models.CharField(max_length=12, verbose_name='Shop Phone')),
                ('shop_logo', models.ImageField(upload_to='shopImage/', verbose_name='Image Logo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.category', verbose_name='Category')),
            ],
        ),
    ]
