# Generated by Django 3.2.9 on 2021-12-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.IntegerField(choices=[(1, 'submited'), (2, 'draft'), (3, 'deleted')], default=1, max_length=50, verbose_name='Status'),
        ),
    ]
