# Generated by Django 3.2.9 on 2022-01-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20220101_0549'),
        ('Shop', '0005_alter_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.supplier', verbose_name='Supplier'),
        ),
    ]
