# Generated by Django 3.2.9 on 2022-01-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_customer_password'),
        ('Shop', '0015_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.supplier', verbose_name='Supplier'),
        ),
    ]
