# Generated by Django 3.2.9 on 2022-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_alter_shop_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='productImage/', verbose_name='Product Main Image'),
        ),
    ]
