# Generated by Django 3.2.9 on 2021-12-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Price')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('order_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Discount Percent')),
                ('discount_available', models.BooleanField(default=False, verbose_name='Discount Available')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Payment Type')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('payment_status', models.CharField(max_length=50, verbose_name='Payment Status')),
            ],
        ),
    ]
