# Generated by Django 3.2.9 on 2021-12-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_orderitems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'submited'), (2, 'canceled'), (3, 'deleted')], default=1, verbose_name='Status'),
        ),
    ]
