# Generated by Django 3.2.9 on 2022-01-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_orders_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'submited'), (2, 'canceled'), (3, 'draft'), (4, 'Paied')], default=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Price'),
        ),
    ]
