# Generated by Django 3.2.9 on 2022-01-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_auto_20220106_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price'),
        ),
    ]
