# Generated by Django 3.2.9 on 2022-01-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_orderitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount Percent'),
        ),
    ]
