# Generated by Django 3.2.9 on 2022-01-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_alter_product_discount'),
        ('Orders', '0011_alter_orders_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.shop', verbose_name='source shop'),
        ),
    ]
