# Generated by Django 3.2.9 on 2022-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_alter_orders_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='update_at',
            field=models.DateField(blank=True, null=True, verbose_name='Update at'),
        ),
    ]
