# Generated by Django 3.2.9 on 2022-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_alter_shop_supplier'),
        ('Orders', '0014_alter_orders_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(through='Orders.OrderItems', to='Shop.Product'),
        ),
    ]
