# Generated by Django 3.2.9 on 2022-01-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_remove_orderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
